using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace GraduatedCylinder.Roslyn.IoT;

[Generator]
public class UnitPreferencesGenerator : BaseGenerator
{

    public UnitPreferencesGenerator()
        : base("GraduatedCylinder.IoT") { }

    protected override void ExecuteInternal(GeneratorExecutionContext context) {
        if (context.SyntaxReceiver is not DimensionReceiver receiver) {
            return;
        }
        //Debugger.Launch();

        string filename = "UnitPreferences.g.cs";

        WriteAutoGeneratedNotification();

        Buffer.AppendLine("using System;");
        Buffer.AppendLine();
        Buffer.AppendLine("namespace GraduatedCylinder;");
        Buffer.AppendLine("");
        Buffer.AppendLine("public partial class UnitPreferences {");
        Buffer.AppendLine("");
        Buffer.AppendLine("");

        foreach (StructDeclarationSyntax @struct in receiver.GetDimensions(context.Compilation)) {
            Log($"Generating for {@struct.Identifier}");
            NameSet names = NameSet.FromDimensionType(@struct.Identifier.ToString());

            Buffer.AppendLine();
            Buffer.AppendLine($"\tpublic {@struct.Identifier}Unit {@struct.Identifier}Unit {{ get; set; }}");

        }

        Buffer.AppendLine("}");

        //don't add to the IoT.dll
        BufferToGeneratedFile(filename).AddToContext(context);

    }

    protected override void InitializeInternal(GeneratorInitializationContext context) {
        context.RegisterForSyntaxNotifications(() => new DimensionReceiver());
    }

}