using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace GraduatedCylinder.Roslyn.Full;

[Generator]
public class UnitPreferences64Generator : BaseGenerator
{

    public UnitPreferences64Generator()
        : base("GraduatedCylinder") { }

    protected override void ExecuteInternal(GeneratorExecutionContext context) {
        if (context.SyntaxReceiver is not DimensionReceiver receiver) {
            return;
        }
        //Debugger.Launch();

        string filename = "UnitPreferences.g.cs";

        WriteAutoGeneratedNotification();

        Buffer.AppendLine("using System;");
        Buffer.AppendLine();
        Buffer.AppendLine("namespace GraduatedCylinder;");
        Buffer.AppendLine();
        Buffer.AppendLine("public partial class UnitPreferences {");
        Buffer.AppendLine();

        foreach (StructDeclarationSyntax @struct in receiver.GetDimensions(context.Compilation)) {
            Log($"Generating for {@struct.Identifier}");
            NameSet names = NameSet.FromDimensionType(@struct.Identifier.ToString());

            Buffer.AppendLine($"\tpublic {@struct.Identifier}Unit {@struct.Identifier}Unit {{ get; set; }}");
            Buffer.AppendLine();
            Buffer.AppendLine($"\tpublic void Fix({@struct.Identifier} value) {{");
            Buffer.AppendLine($"\t\tvalue.Units = {@struct.Identifier}Unit;");
            Buffer.AppendLine("\t}");
            Buffer.AppendLine();
        }

        Buffer.AppendLine("}");

        BufferToGeneratedFile(filename).AddToContext(context);
    }

    protected override void InitializeInternal(GeneratorInitializationContext context) {
        context.RegisterForSyntaxNotifications(() => new DimensionReceiver());
    }

}