name: Publish

on:
  release:
    types:
      - published

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  GraduatedCylinder: 'D:\a\GraduatedCylinder\GraduatedCylinder\'
  NugetApiKey: ${{ secrets.NUGET_API_KEY }}
  
jobs:
  publish:
    name: Build, Test, and Publish
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      
      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v3
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
            !~/.nuget/packages/GraduatedCylinder
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
          
      - name: Run './build.cmd Clean Test PushToNuGet'
        run: ./build.cmd Clean Test PushToNuGet
      
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: Artifacts
